In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("UNSW-NB15_1.csv")
data

C:\Users\Administrator\AppData\Local\Temp\ipykernel_13820\4256207068.py:1: DtypeWarning: Columns (43) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("UNSW-NB15_1.csv")

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.001055,udp,dns,CON,2,2,132,164,947.867306,...,1,1,0,0,0,3,7,0,NaN,0
1,2,0.036133,udp,-,CON,4,4,528,304,83.026597,...,1,2,0,0,0,3,4,0,NaN,0
2,3,0.001119,udp,dns,CON,2,2,146,178,893.655019,...,1,1,0,0,0,2,8,0,NaN,0
3,4,0.001209,udp,dns,CON,2,2,132,164,827.129853,...,1,1,0,0,0,1,9,0,NaN,0
4,5,0.001169,udp,dns,CON,2,2,146,178,855.431935,...,1,1,0,0,0,1,9,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699996,699997,0.020383,tcp,-,FIN,6,8,320,1874,245.609088,...,1,4,0,0,0,5,20,0,NaN,0
699997,699998,1.402957,tcp,http,FIN,364,746,19410,1087890,258.743560,...,2,2,0,0,4,7,1,0,NaN,0
699998,699999,0.007108,tcp,-,FIN,24,24,2158,2464,3237.224861,...,1,2,0,0,0,7,13,0,NaN,0
699999,700000,0.004435,udp,-,CON,4,4,568,304,676.437445,...,1,3,0,0,0,5,13,0,NaN,0
700000,700001,0.072974,tcp,-,FIN,72,72,4238,60788,973.149820,...,1,2,0,0,0,7,13,0,NaN,0

In [3]:
value_counts = data["label"].value_counts()
count_0 = data['label'].value_counts().get(0, 0)
count_1 = data['label'].value_counts().get(1, 0)
total_samples = len(data)
count_1 / total_samples

0.03173566894904436

In [4]:
desired_count_0 = int(100000 * count_0 / total_samples)
desired_count_1 = int(100000 * count_1 / total_samples)

data_0 = data[data['label'] == 0].sample(n=desired_count_0, replace=True)
data_1 = data[data['label'] == 1].sample(n=desired_count_1, replace=True)

filtered_data = pd.concat([data_0, data_1])

filtered_data = filtered_data.reset_index(drop=True)

filtered_data

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,402569,0.140580,tcp,ssh,FIN,102,102,14616,17238,718.466720,...,1,2,0,0,0,2,1,0,NaN,0
1,534707,1.184566,tcp,http,FIN,14,18,1684,10168,10.976489,...,1,1,0,0,1,2,2,0,NaN,0
2,104396,0.000965,udp,dns,CON,2,2,130,162,1036.269471,...,1,1,0,0,0,2,4,0,NaN,0
3,528881,0.153902,tcp,-,FIN,40,40,2542,19502,253.464254,...,1,1,0,0,0,3,1,0,NaN,0
4,608721,0.319568,tcp,-,FIN,122,126,7810,15664,378.636961,...,1,1,0,0,0,2,11,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99994,134503,0.000010,udp,dns,INT,2,0,114,0,100000.000000,...,4,4,0,0,0,4,16,0,Generic,1
99995,134392,0.000010,udp,dns,INT,2,0,114,0,100000.000000,...,1,1,0,0,0,1,14,0,Generic,1
99996,85215,0.000003,unas,-,INT,2,0,200,0,200000.000000,...,4,4,0,0,0,4,12,0,Analysis,1
99997,6441,0.480929,tcp,http,FIN,10,8,566,354,18.735824,...,1,3,0,0,1,3,11,0,Fuzzers,1
99998,25938,0.239712,sctp,-,CON,4,2,840,440,12.515018,...,2,2,0,0,0,3,3,0,Exploits,1

In [5]:
filtered_data.to_csv('unsupervised_data.csv', index=False)